Script changes:
  - packages/scripts/**/*

Infrastructure changes:
  - packages/deployment/**/*
  - packages/*/src/aws/**/*

Implementation changes:
  - packages/*/src/**/*
  - !packages/*/src/aws/**/*
