name: Lint Code

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: Lint Back-end code
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.2.0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - name: Prepare
        run: pnpm i
      - name: Build
        run: pnpm compile
      - name: Lint Back-end
        run: pnpm lint
