name: Slack notification

on:
  pull_request:

    branches: [main]
    types: [opened, synchronize, ready_for_review]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  slackNotification:
    if: false
    name: Send Slack notifications
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: New PR
        if: github.event.action == 'opened' && github.event.pull_request.draft == false
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7 #v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
          SLACK_TITLE: PR Created
          SLACK_LINK_NAMES: true
          SLACK_FOOTER: ''
          SLACK_MESSAGE: |
            @here
            utils
            ${{ github.event.pull_request.title }}
            https://github.com/nRFCloud/ts-json-schema-transformer/pull/${{ github.event.number }}
      - name: PR Ready for Review
        if: github.event.action == 'ready_for_review' && github.event.pull_request.draft == false
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7 #v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
          SLACK_TITLE: PR Ready for Review
          SLACK_LINK_NAMES: true
          SLACK_FOOTER: ''
          SLACK_MESSAGE: |
            @here
            utils
            ${{ github.event.pull_request.title }}
            https://github.com/nRFCloud/ts-json-schema-transformer/pull/${{ github.event.number }}
      - name: Updated PR
        if: github.event.action == 'synchronize' && github.event.pull_request.draft == false
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7 #v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
          SLACK_TITLE: PR Updated
          SLACK_FOOTER: ''
          SLACK_MESSAGE: |
            utils
            ${{ github.event.pull_request.title }}
            https://github.com/nRFCloud/ts-json-schema-transformer/pull/${{ github.event.number }}
